name: Build for Alice Novel

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI
        run: |
          zip -r srfb.zip ./src/* && mv srfb.zip srfb.anproj
      
      # Upload Artifact
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: srfb
          path: srfb.anproj
